ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"
  autoupdate_schedule: quarterly

exclude: |
  (?x)^(
      docs/index.md|
      docs/install.md|
      docs/citing.md|
      docs/overview.md|
      docs/reference.md|
      docs/contributing.md|
      docs/api/invert4geom.rst|
      docs/api/invert4geom.inversion.rst|
      docs/api/invert4geom.plotting.rst|
      docs/api/invert4geom.synthetic.rst|
      docs/api/invert4geom.utils.rst|
      docs/api/invert4geom.cross_validation.rst|
      docs/api/invert4geom.regional.rst|
      docs/api/invert4geom.optimization.rst|
      docs/api/invert4geom.uncertainty.rst|
      docs/_invert4geom_refs.bib|
      CHANGELOG.md|
      .github/ISSUE_TEMPLATE/feature_request.md|
      .github/config.yml|
      .github/workflows/ci.yml|
      binder/environment.yml|
      templates/CHANGELOG.md.j2|
      README.md|
  )$

repos:
  - repo: https://github.com/adamchainz/blacken-docs
    rev: "1.19.1"
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==23.7.0]
        exclude: \.md

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.8.6"
    hooks:
      - id: ruff
        args: ["--fix", "--show-fixes"]
        exclude: \.md
      - id: ruff-format
        exclude: \.md

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-added-large-files
        exclude: ^(docs/examples/bishop_basement_model.ipynb|docs/tutorial/05_density_optimization.ipynb|docs/tutorial/06_reference_level_optimization.ipynb|docs/examples/uieda_et_al_2017_CRUST1.ipynb|docs/quickstart.ipynb|docs/tutorial/02_simple_inversion.ipynb|docs/tutorial/08_combining_it_all.ipynb)
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: "v1.10.0"
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        types_or: [yaml, markdown, html, css, scss, javascript, json]
        args: [--prose-wrap=always]
        exclude: \.md

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.14.1"
    hooks:
      - id: mypy
        files: src|tests
        args: []
        additional_dependencies:
          - pytest
          - types-requests
          # - data-science-types

  - repo: https://github.com/codespell-project/codespell
    rev: "v2.3.0"
    hooks:
      - id: codespell
        name: codespell
        description: Checks for common misspellings in text files.
        entry:
          codespell --skip="*.js,*.html,*.css,*.svg,*.ipynb" -L ore
          --ignore-regex=".*codespell-ignore$"
        args: [--ignore-words-list, montaj]

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: "v0.10.0.1"
    hooks:
      - id: shellcheck

  # check for commonly miss-capitalized words
  - repo: local
    hooks:
      - id: disallow-caps
        name: Disallow improper capitalization
        language: pygrep
        entry: PyBind|Numpy|Cmake|CCache|Github|PyTest
        exclude: .pre-commit-config.yaml

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: "v0.23"
    hooks:
      - id: validate-pyproject
        additional_dependencies: ["validate-pyproject-schema-store[all]"]

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.30.0"
    hooks:
      - id: check-dependabot
      - id: check-github-workflows
      - id: check-readthedocs
