name: invert4geom
channels:
  - conda-forge
dependencies:
  - python==3.11
  - invert4geom==0.5
  # optimization
  - optuna>=3.1.0 # need JournalStorage
  - optuna-integration
  - botorch>=0.4.0
  - joblib
  - psutil
  # visualization
  - pyvista
  - trame
  - ipywidgets
  - matplotlib
  - seaborn
  - ipython
  - pip
  - pip:
    - tqdm_joblib