name: invert4geom
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - affine=2.4.0
  - asciitree=0.3.3
  - attrs=23.2.0
  - aws-c-auth=0.7.17
  - aws-c-cal=0.6.11
  - aws-c-common=0.9.15
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.7
  - aws-c-mqtt=0.10.3
  - aws-c-s3=0.5.7
  - aws-c-sdkutils=0.1.15
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.6
  - aws-sdk-cpp=1.11.267
  - blosc=1.21.5
  - bokeh=3.4.1
  - branca=0.7.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.2.2
  - cairo=1.18.0
  - certifi=2024.2.2
  - cfitsio=4.3.1
  - cftime=1.6.3
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - contourpy=1.2.1
  - curl=8.7.1
  - cycler=0.12.1
  - cytoolz=0.12.3
  - dask=2024.4.2
  - dask-core=2024.4.2
  - dask-expr=1.0.12
  - dcw-gmt=2.1.2
  - distributed=2024.4.2
  - docrep=0.3.2
  - et_xmlfile=1.1.0
  - expat=2.6.2
  - fasteners=0.17.3
  - fftw=3.3.10
  - fiona=1.9.5
  - folium=0.16.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.51.0
  - freetype=2.12.1
  - freexl=2.0.0
  - fsspec=2024.3.1
  - future=1.0.0
  - gdal=3.8.1
  - geopandas=0.14.3
  - geopandas-base=0.14.3
  - geos=3.12.1
  - geotiff=1.7.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - ghostscript=10.03.0
  - giflib=5.2.2
  - glog=0.7.0
  - gmt=6.4.0
  - gshhg-gmt=2.3.7
  - harmonica=0.6.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - icu=73.2
  - idna=3.7
  - importlib-metadata=7.1.0
  - importlib_metadata=7.1.0
  - invert4geom=0.4.0
  - jinja2=3.1.3
  - joblib=1.4.0
  - json-c=0.17
  - kealib=1.5.3
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.1
  - libaec=1.1.3
  - libarchive=3.7.2
  - libarrow=15.0.2
  - libarrow-acero=15.0.2
  - libarrow-dataset=15.0.2
  - libarrow-flight=15.0.2
  - libarrow-flight-sql=15.0.2
  - libarrow-gandiva=15.0.2
  - libarrow-substrait=15.0.2
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libboost-headers=1.84.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.7.1
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgdal=3.8.1
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.4
  - libgomp=13.2.0
  - libgoogle-cloud=2.23.0
  - libgoogle-cloud-storage=2.23.0
  - libgrpc=1.62.2
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm16=16.0.6
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libnl=3.9.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libparquet=15.0.2
  - libpng=1.6.43
  - libpq=16.2
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librttopo=1.1.0
  - libspatialindex=1.9.3
  - libspatialite=5.1.0
  - libsqlite=3.45.3
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxml2=2.12.6
  - libzip=1.10.1
  - libzlib=1.2.13
  - llvmlite=0.42.0
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.6.1
  - markupsafe=2.1.5
  - matplotlib-base=3.8.4
  - minizip=4.0.5
  - msgpack-python=1.0.7
  - munkres=1.1.4
  - ncurses=6.4.20240210
  - netcdf4=1.6.5
  - networkx=3.3
  - nptyping=2.5.0
  - nspr=4.35
  - nss=3.98
  - numba=0.59.1
  - numba-progress=1.1.0
  - numcodecs=0.12.1
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openpyxl=3.1.2
  - openssl=3.2.1
  - orc=2.0.0
  - packaging=24.0
  - pandas=2.2.2
  - partd=1.4.1
  - pcre=8.45
  - pcre2=10.42
  - pillow=10.3.0
  - pip=24.0
  - pixman=0.43.2
  - platformdirs=4.2.0
  - polartoolkit=0.3.1
  - pooch=1.8.1
  - poppler=23.12.0
  - poppler-data=0.4.12
  - postgresql=16.2
  - proj=9.3.1
  - psutil=5.9.8
  - pthread-stubs=0.4
  - pyarrow=15.0.2
  - pyarrow-hotfix=0.6
  - pygmt=0.11.0
  - pykdtree=1.3.12
  - pyogrio=0.7.2
  - pyparsing=3.1.2
  - pyproj=3.6.1
  - pysocks=1.7.1
  - python=3.12.3
  - python-dateutil=2.9.0
  - python-dotenv=1.0.1
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytz=2024.1
  - pyyaml=6.0.1
  - rasterio=1.3.9
  - rdma-core=51.0
  - re2=2023.09.01
  - readline=8.2
  - requests=2.31.0
  - rioxarray=0.15.5
  - rtree=1.2.0
  - s2n=1.4.12
  - scikit-learn=1.4.2
  - scipy=1.13.0
  - setuptools=69.5.1
  - shapely=2.0.4
  - six=1.16.0
  - snappy=1.2.0
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - sqlite=3.45.3
  - tblib=3.0.0
  - threadpoolctl=3.4.0
  - tiledb=2.18.2
  - tk=8.6.13
  - toolz=0.12.1
  - tornado=6.4
  - tqdm=4.66.2
  - typish=1.9.3
  - tzcode=2024a
  - tzdata=2024a
  - ucx=1.15.0
  - uriparser=0.9.7
  - urllib3=2.2.1
  - verde=1.8.0
  - wheel=0.43.0
  - xarray=2024.3.0
  - xerces-c=3.2.5
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xrft=1.0.1
  - xyzservices=2024.4.0
  - xz=5.2.6
  - yaml=0.2.5
  - zarr=2.17.2
  - zict=3.0.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip
  - pip:
    - optuna>=3.1.0
    - botorch>=0.4.0
    - joblib
    - psutil
    - tqdm_joblib
    - pyvista
    - trame
    - ipywidgets
    - matplotlib
    - seaborn
    - ipython
