name: semantic_release_check

# define when this workflow is triggered
on:
  workflow_dispatch:
  pull_request:

# cancel pending or running jobs of only this workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # dry run of semantic release without changing anything
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      # checkout the repo and supply a PAT for the changelog update commit.
      - id: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # use semantic-release in no operation mode
      - id: semantic-release
        uses: python-semantic-release/python-semantic-release@master
        with:
          root_options: --noop
